### ISSUE TITLE
init function for MCP230xx assumes part is operating with IOCON.BANK = 0

### ISSUE THREAD

**Issue by wvolz** [adafruit/Adafruit_Python_GPIO#56]
- Platform/operating system:
```
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie
```
- Python version (run `python -version` or `python3 -version`): Python 2.7.9

- Error message you are receiving, including any Python exception traces:  Writes/reads do not work as expected when part was operated in IOCON.BANK=1 mode previously

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): 
    1. ```i2cset -y 1 0x20 0x0A 0x80```
    2. use the example char_lcd_plate.py from [Adafruit_Python_CharLCD](https://github.com/adafruit/Adafruit_Python_CharLCD) and observe no output

The char_lcd_plate script showcases the issue, but the root of the problem is that the MCP part should be reset to IOCON.BANK=0 before using it. The current script assumes it is in this mode. It would also be a good idea to reset registers to their POR value.

**Comment by ladyada** [comment]
hiya thank you for the issue. we're going to be deprecating this library in favor of [our python3 Blinka library](https://github.com/adafruit/Adafruit_Blinka) which has [support for almost 200 different drivers](https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html), and a [wide variety of linux computers](https://circuitpython.org/blinka) as well as [ft232h
](https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h)
If this issue is still occuring when you use Blinka, please re-open it there!
