### ISSUE TITLE
Expose polarity argument on BBIO_PWM_Adapter.start()

### ISSUE THREAD

**Issue by dplanella** [adafruit/Adafruit_Python_GPIO#76]
Adafruit's dedicated Beaglebone Black Python API allows the use of the `polarity` argument upon calling `PWM.start()`, which determines whether the duty cycle setting affects the high or low part of the signal's period.

This is useful in cases where an output is driven with inverted logic (e.g. using a transistor in inverter configuration to switch a +12V load).

`BBIO_PWM_Adapter.start()` in the PWM.py module does neither expose nor initialise the `polarity` argument, thus it can't be used.

**Comment by ladyada** [comment]
hiya thank you for the issue. we're going to be deprecating this library in favor of [our python3 Blinka library](https://github.com/adafruit/Adafruit_Blinka) which has [support for almost 200 different drivers](https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html), and a [wide variety of linux computers](https://circuitpython.org/blinka) as well as [ft232h
](https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h)
If this issue is still occuring when you use Blinka, please re-open it there!
