### ISSUE TITLE
Library needs support for Odroid-C2 (ubuntu)

### ISSUE THREAD

**Issue by dan-cristian** [adafruit/Adafruit_Python_GPIO#90]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  
Linux odroid 3.16.60-28 #1 SMP PREEMPT Thu Nov 15 06:06:45 -02 2018 aarch64 aarch64 aarch64 GNU/Linux

- Python version (run `python -version` or `python3 -version`):  
Python 2.7.15rc1

- Error message you are receiving, including any Python exception traces:  Could not determine default I2C bus for platform.

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): 
Issue seems to be in I2C.py file, get_default_bus():
please change so that default bus 1 is returned for Odroid C2 rather than an exception.
I have already tested with above change and it works well.

**Comment by ladyada** [comment]
hiya thank you for the issue. we're going to be deprecating this library in favor of [our python3 Blinka library](https://github.com/adafruit/Adafruit_Blinka) which has [support for almost 200 different drivers](https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html), and a [wide variety of linux computers](https://circuitpython.org/blinka) as well as [ft232h
](https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h)
If this issue is still occuring when you use Blinka, please re-open it there!
